config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

# A user can see all the lists
get '/lists', to: 'lists#index'

# A user can see the details of a given list and its name
get '/lists/new', to: 'lists#new'
post '/lists', to: 'lists#create'

get '/lists/:id', to: 'lists#show', as: :list

# A user can add a new bookmark (movie/list pair) to an existing list
get '/lists/:list_id/bookmarks/newbookmark', to: 'bookmarks#newbookmark', as: :add_bookmarks
post '/lists/:list_id/bookmarks', to: 'bookmarks#create', as: :list_bookmarks

# A user can delete a bookmark from a list
delete '/bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmarks

end


# Features
# Once again, you must have a precise idea of the features of your app in order to build your routes. Here is the list of features:

# A user can see all the lists
# GET "lists"
# A user can see the details of a given list and its name
# GET "lists/42"
# A user can create a new list
# GET "lists/new"
# POST "lists"
# 4 - Routing, Controller, Views for bookmarks
# A user can add a new bookmark (movie/list pair) to an existing list
# Checkout simple_form docs about f.association to easily create a select dropdown for our list of movies.
# GET "lists/42/bookmarks/new"
# POST "lists/42/bookmarks"
# A user can delete a bookmark from a list. How can we make a delete link again?
# DELETE "bookmarks/25"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  before_destroy :bookmarks?

  private

  def bookmarks?
    return unless bookmarks.any?

    raise ActiveRecord::InvalidForeignKey
  end
end

# raise ActiveRecord::RecordNotDestroyed, "Cannot delete movie with associated bookmarks"

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def newbookmark
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "newbookmark"
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      # puts "That movie had already been chosen"
      render "new"
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/newbookmark.html.erb
<h1 class="text-center">Bookmarks</h1>
<div class="container">
  <%= simple_form_for [@list, @bookmark], url: list_bookmarks_path(@list) do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%# <%= f.association :list %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('/assets/images/movie-theater-4609877.jpg');">
  <div class="container">
    <h1 class="text-center">Save any kind of movie</h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="cards">
      <% @lists.each do |list| %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= list.movie.poster_url %>);">
          <h2><%= list.name %></h2>
          <ul class="list-group mb-3">
            <% list.bookmarks.each do |bookmark| %>
              <li class="list-group-item">
                <%= bookmark.movie.title %>
              </li>
            <% end %>
          </ul>
          <%= link_to "View List", list_path(list), class: 'btn btn-primary' %>
        </div>
      <% end %>
      <%= link_to "Create a movie list", new_list_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h1 class="text-center">Create a new movie list</h1>
<div class="container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :name %>
    <%= f.button :submit, class: 'btn btn-primary'%>
  <% end %>
</div>
  <%# create_table "lists", force: :cascade do |t|
    t.string "name"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
  end %>

app/views/lists/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1><%= @list.name %></h1>

        <ul class="list-group mb-3">
        <% @bookmarks.each do |bookmark| %>
          <li class="list-group-item">
            <%= bookmark.movie.title %><br>
            <%= bookmark.movie.overview %><br>
            <%= bookmark.movie.rating %><br>
            <%= bookmark.comment %><br>

            <%= link_to 'Delete',
              delete_bookmarks_path(bookmark),
              data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to delete this movie?' },
              class: 'btn btn-primary'
            %>
          </li>
        <% end %>
      </ul>

      <%= link_to "Add a movie", add_bookmarks_path(@list), class: 'btn btn-primary' %>


    </div>
  </div>
</div>

<%# Bookmark class
id: 1,
  comment: "Example comment",
  movie_id: 2,
  list_id: 1,
  created_at: Sat, 15 Jul 2023 03:41:19.698256000 UTC +00:00,
  updated_at: Sat, 15 Jul 2023 03:41:19.698256000 UTC +00:00>,

Movie class
  title: "Titanic",
  overview: "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic.",
  poster_url: "https://image.tmdb.org/t/p/original/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  rating: 7.9, %>